# Changing this file necessitates a server restart
name: "Journal of Open Source Software"
abbreviation: "JOSS"
tagline: "a <strong>developer friendly</strong>, open access journal for research software packages."
logo_url: "http://joss.theoj.org/logo_large.jpg"
url: "http://joss.theoj.org"
editor_email: "admin@theoj.org"
noreply_email: "noreply@joss.theoj.org"
twitter: "@JOSS_TheOJ"
twitter_issn: "2475-9066"
google_analytics: "UA-47852178-4"
github: "openjournals/joss"
reviews: "openjournals/joss-reviews"
papers_html_url: "https://www.theoj.org/joss-papers"
papers_repo: "openjournals/joss-papers"
product: "software" # the *thing* being submitted for review
reviewers: "https://bit.ly/joss-reviewers"
submission_enquiry: |-
  **Project repository URL:** INSERT YOUR REPOSITORY LINK HERE

  Briefly describe your software, its research application and any questions you have about the JOSS submission criteria.
paper_types: []
