# Changing this file necessitates a server restart
name: "The Journal of Open Source Software"
abbreviation: "JOSS"
issn: "2475-9066"
tagline: "a <strong>developer friendly</strong> journal for research software packages."
logo_url: "http://joss.theoj.org/logo_large.png"
url: "http://joss.theoj.org"
editor_email: "joss.theoj@gmail.com"
noreply_email: "noreply@joss.theoj.org"
twitter: "@JOSS_TheOJ"
google_analytics: "UA-47852178-4"
google_site_verification: "7Gu5e95ah9hH-lXs1j7OVC2dKQ8rVGEKz1SjvR2XI"
github: "openjournals/joss"
reviews: "openjournals/joss-reviews-testing"
papers_repo: "openjournals/joss-papers-testing"
papers_html_url: "https://www.theoj.org/joss-papers"
product: "software" # the *thing* being submitted for review
reviewers: "https://bit.ly/joss-reviewers"
submission_enquiry: |-
  **Project repository URL:** INSERT YOUR REPOSITORY LINK HERE

  Briefly describe your software, its research application and any questions you have about the JOSS submission criteria.
paper_types: []
