# Changing this file necessitates a server restart
name: "The Journal of Open Source Software"
abbreviation: "JOSS"
issn: "2475-9066"
tagline: "a <strong>developer friendly</strong> journal for research software packages."
logo_url: "http://joss.theoj.org/logo_large.png"
url: "http://joss.theoj.org"
editor_email: "joss.theoj@gmail.com"
noreply_email: "noreply@joss.theoj.org"
twitter: "@JOSS_TheOJ"
mastodon_url: "https://fosstodon.org/@JOSS"
google_analytics: "UA-47852178-4"
github: "openjournals/joss"
reviews: "openjournals/joss-reviews-testing"
papers_repo: "openjournals/joss-papers-testing"
papers_html_url: "https://www.theoj.org/joss-papers"
reviewers_url: "https://reviewers.joss.theoj.org"
reviewers_signup_url: "https://reviewers.joss.theoj.org/join"
reviewers_lookup_url: "https://reviewers.joss.theoj.org/lookup"
product: "software" # the *thing* being submitted for review
submission_enquiry: |-
  **Project repository URL:** INSERT YOUR REPOSITORY LINK HERE

  Briefly describe your software, its research application and any questions you have about the JOSS submission criteria.
paper_types: []
bot_username: editorialbot
