# Changing this file necessitates a server restart
name: "Proceedings of the JuliaCon Conferences"
abbreviation: "JCON"
issn: "2642-4029"
tagline: "an open-access journal published in cooperation with the <a href='http://www.theoj.org/'>the Open Journals</a>."
logo_url: "http://proceedings.juliacon.org/logo_large.jpg"
url: "https://proceedings.juliacon.org"
editor_email: "admin@theoj.org"
noreply_email: "admin@theoj.org"
launch_date: "2019-06-01"
twitter: "@juliaconorg"
mastodon_url: "FIXME"
google_analytics: "UA-47852178-9"
github: "openjournals/joss"
reviews: "JuliaCon/proceedings-review"
papers_repo: "JuliaCon/proceedings-paper"
papers_html_url: "https://juliacon.github.io/proceedings-papers"
reviewers_url: "https://bit.ly/2V9GSFq"
reviewers: "https://bit.ly/2V9GSFq"
reviewers_signup_url: "https://forms.gle/Zr9jNaWg45qkAWKT6"
reviewers_lookup_url: "https://bit.ly/2V9GSFq"
product: "paper" # the *thing* being submitted for review
submission_enquiry: |-
  **Project repository URL:** INSERT YOUR REPOSITORY LINK HERE

  Briefly describe your software, its research application and any questions you have about the JulianCon submission criteria.
paper_types: ["full paper", "extended abstract"]
bot_username: editorialbot
features:
  tracks: true
