# Changing this file necessitates a server restart
name: "Journal of Open Source Software"
abbreviation: "TEST_JOURNAL"
issn: "2475-9066"
tagline: "a <strong>developer friendly</strong>, open access journal for research software packages."
logo_url: "https://test.joss.theoj.org/logo_large.jpg"
url: "https://test.joss.theoj.org"
editor_email: "admin@theoj.org"
noreply_email: "admin@theoj.org"
twitter: "@JOSS_TheOJ"
mastodon_url: "https://fosstodon.org/@JOSS"
google_analytics: "UA-47852178-4"
github: "openjournals/joss"
reviews: "openjournals/joss-reviews-testing"
papers_html_url: "https://www.theoj.org/joss-papers-testing"
reviewers_signup_url: "https://reviewers.joss.theoj.org/join"
papers_repo: "openjournals/joss-papers-testing"
product: "software" # the *thing* being submitted for review
reviewers: "https://bit.ly/joss-reviewers"
submission_enquiry: |-
  **Project repository URL:** INSERT YOUR REPOSITORY LINK HERE

  Briefly describe your software, its research application and any questions you have about the JOSS submission criteria.
paper_types: []
bot_username: botsci
