name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          bundler-cache: true
      - name: Install Elasticsearch
        uses: ankane/setup-elasticsearch@v1
        with:
          elasticsearch-version: 7.12.0
      - name: Verify Elasticsearch connection and create index
        env:
          ELASTICSEARCH_URL: http://localhost:9200
        run: |
          echo $ELASTICSEARCH_URL
          curl -fsSL "$ELASTICSEARCH_URL/_cat/health?h=status"
          curl -X PUT $ELASTICSEARCH_URL/jose-production
      - name: Run tests
        env:
          ELASTICSEARCH_URL: http://localhost:9200
          PGUSER: postgres
          PGPASSWORD: secret
          RAILS_ENV: test
          GH_SECRET: 12345
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load
          bundle exec rails spec
